version: "3.7"

services:
  database: 
    image: postgres
    container_name: iffolha_database
    restart: always
    ports: 
      - 8081:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=iffolha
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: iffolha
    restart: always
    environment:
      - DATABASE_URL=postgresql://docker:ignite@iffolha_database:5432/iffolha
    ports: 
      - 8888:8888
      - 5000:5000
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local